spring:
  jwt:
    secret: ZGF5b25lLXNwcmluZy1ib290LWRpdmlkZW5kLXByb2plY3QtdHV0b3JpYWwtand0LXNlY3JldC1rZXkK
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/withme?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: withus
    password: withuspassword
  data:
    redis:
      host: host.docker.internal
      port: 6379
  elasticsearch:
    uri: ${ ELASTICSEARCH_URI }
cloud:
  aws:
    s3:
      bucket: ${ BUCKET_NAME }
    stack:
      auto: false
