spring:
  jwt:
    secret: ZGF5b25lLXNwcmluZy1ib290LWRpdmlkZW5kLXByb2plY3QtdHV0b3JpYWwtand0LXNlY3JldC1rZXkK
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/withme?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: withus
    password: withuspassword
  data:
    redis:
      host: host.docker.internal
      port: 6379
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  rabbitmq:
    username: "withus"
    password: "withuspassword"
    stream:
      host: ${RABBITMQ_HOST}
      port: ${RABBITMQ_PORT}
  elasticsearch:
    uri: ${ELASTICSEARCH_URI}

cool-sms:
  api-key: cool-sms.api-key
  api-secret-key: cool-sms.api-secret-key
  domain: https://api.coolsms.co.kr
  sender-phone-number: cool-sms.sender-phone-number
auth-sms-service:
  text-content-template: "[with me] 인증 문자는 [%s] 입니다."
  expiration-seconds: 60
  auth-code-length: 6
redis:
  key:
    prefix:
      auth-sms: "AuthSms: "

cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    stack:
      auto: false